discordToken: "your-discord-token-here"
updatesChannelID: "your-updates-channel-id-here"
discordServerID: "your-discord-server-id-here"

joinMessage: "`{player}` joined the Server!"
leaveMessage: "`{player}` left the Server!"