discordToken: "YOUR_BOT_TOKEN"
discordServerID: "YOUR_DISCORD_SERVER_ID"
updatesChannelID: "YOUR_DISCORD_CHANNEL_ID"
statusChannelID: "YOUR_STATUS_CHANNEL_ID"
statusMessageID: "YOUR_STATUS_MESSAGE_ID"
sendJoinMessage: true
sendLeaveMessage: true
joinMessage: "`{player}` joined the Server!"
leaveMessage: "`{player}` left the Server!"